import { ReadEntry } from '@/types/read';

export const INITIAL_READ_LIST: ReadEntry[] = [
  {
    id: 'read-s1',
    anilistId: 119257,
    title: 'Omniscient Reader\'s Viewpoint',
    romajiTitle: 'Jeonjijeok Dokja Sijeom',
    nativeTitle: '전지적 독자 시점',
    comicFormat: 'MANHWA',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx119257-Wc1zQp0e.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/119257-b248a3b5.jpg',
    status: 'READING',
    publishStatus: 'RELEASING',
    rating: 10,
    currentChapter: 195,
    totalChapters: 220,
    platform: 'Webtoon (Official)',
    genres: ['Action', 'Fantasy', 'Supernatural'],
    author: 'sing N song / Sleepy-C',
    releaseYear: '2020',
    review: 'Salah satu manhwa terbaik dengan cerita paling cerdas. Hubungan antara Kim Dokja dan Yoo Joonghyuk ditulis dengan sangat mendalam.',
    notes: `### Catatan Skenario:
- Dokja selalu mengorbankan dirinya demi menyelamatkan anggota kelompoknya.
- Skenario Dokkaebi King dan konstelasi sponsor luar biasa seru.`,
    startDate: '2022-04-10',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'read-s2',
    anilistId: 30013,
    title: 'One Piece',
    romajiTitle: 'ONE PIECE',
    nativeTitle: 'ONE PIECE',
    comicFormat: 'MANGA',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx30013-1YQh40c9.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/30013-n736a5a2.jpg',
    status: 'READING',
    publishStatus: 'RELEASING',
    rating: 10,
    currentChapter: 1115,
    totalChapters: 1125,
    platform: 'MangaPlus (Shueisha)',
    genres: ['Action', 'Adventure', 'Fantasy'],
    author: 'Eiichiro Oda',
    releaseYear: '1997',
    review: 'Karya agung abad ini. Arc Egghead Island membongkar banyak rahasia Void Century, Gorosei, dan siaran Dr. Vegapunk.',
    notes: `### Catatan Lore Penting:
- Joy Boy adalah bajak laut pertama dalam sejarah 800 tahun lalu.
- Robot Kuno Iron Giant bergerak karena genderang drum pembebasan (Gear 5).`,
    startDate: '2015-01-01',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'read-s3',
    anilistId: 105398,
    title: 'Solo Leveling',
    romajiTitle: 'Na Honjaman Rebeleop',
    nativeTitle: '나 혼자만 레벨업',
    comicFormat: 'MANHWA',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx105398-b6b1070e.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/105398-7517c5b6.jpg',
    status: 'COMPLETED',
    publishStatus: 'FINISHED',
    rating: 9,
    currentChapter: 179,
    totalChapters: 179,
    platform: 'KakaoPage',
    genres: ['Action', 'Adventure', 'Fantasy'],
    author: 'Chugong / DUBU (REDICE)',
    releaseYear: '2018',
    review: 'Art style legendaris karya almarhum DUBU. Visual efek skill dan komando bayangan "Arise" tidak ada tandingannya.',
    notes: 'Selesai membaca seluruh main story dan side story Jinwoo dengan Cha Hae-in.',
    startDate: '2020-03-12',
    finishDate: '2022-01-05',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'read-s4',
    anilistId: 101517,
    title: 'Jujutsu Kaisen',
    romajiTitle: 'Jujutsu Kaisen',
    nativeTitle: '呪術廻戦',
    comicFormat: 'MANGA',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx101517-5735c0f1.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/101517-c812d3e4.jpg',
    status: 'COMPLETED',
    publishStatus: 'FINISHED',
    rating: 9,
    currentChapter: 271,
    totalChapters: 271,
    platform: 'MangaPlus',
    genres: ['Action', 'Fantasy', 'Supernatural'],
    author: 'Gege Akutami',
    releaseYear: '2018',
    review: 'Pertarungan puncak Shinjuku Showdown melawan Ryomen Sukuna berlangsung sangat intens.',
    startDate: '2021-06-15',
    finishDate: '2024-09-30',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'read-s5',
    anilistId: 111867,
    title: 'Nano Machine',
    romajiTitle: 'Nanomasin',
    nativeTitle: '나노마신',
    comicFormat: 'MANHWA',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx111867-a821e25e.jpg',
    bannerImage: 'https://s4.anilist.co/file/anilistcdn/media/manga/banner/111867-b8449c02.jpg',
    status: 'PLAN_TO_READ',
    publishStatus: 'RELEASING',
    rating: 0,
    currentChapter: 0,
    totalChapters: 215,
    platform: 'Webtoon',
    genres: ['Action', 'Murim', 'Sci-Fi'],
    author: 'Jeolmu Hyeon / GGBG',
    releaseYear: '2020',
    review: 'Rekomendasi dari teman untuk manhwa tema murim kultivasi pedang modern.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
